package com.nish.api.model;

import org.ehcache.Cache;

import java.util.Objects;

/**
 * Represents the details of a cache, including the cache instance, key type, and value type.
 * This class encapsulates a cache and provides methods to access its key and value types.
 *
 * @param <K> the type of the cache key
 * @param <V> the type of the cache value
 */
public record CacheDetail<K, V>(Cache<K, V> cache, Class<K> keyType, Class<V> valueType) {
  /**
   * Constructs a new CacheDetail object with the provided cache, key type, and value type.
   * <p>
   * This constructor is automatically generated by the record feature. It initializes the cache instance,
   * the key type, and the value type.
   * </p>
   *
   * @param cache     the cache instance
   * @param keyType   the class type of the cache key
   * @param valueType the class type of the cache value
   */
  public CacheDetail {
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (!(o instanceof CacheDetail<?, ?> that)) return false;
    return Objects.equals(cache, that.cache) && Objects.equals(keyType, that.keyType) && Objects.equals(valueType, that.valueType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cache, keyType, valueType);
  }
}
